/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/**
* This example shows how to give your tab bar a custom look and feel typical of
* app navigation.
*/
Ext.define('Mass.view.main.NavigationTabs', {
    extend: 'Ext.tab.Panel',
    xtype: 'navigation-tabs',

       
        otherContent: [{
            type: 'Styles',
            path: 'sass/src/view/tab/NavigationTabs.scss'
        }],
       

        height: 400,
        width: 600,


        ui: 'navigation',
        tabPosition: 'left',
        tabRotation: 0,
        tabBar: {

            border: false
        },

        defaults: {
            textAlign: 'left',
            bodyPadding: 15
        }
        });